spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Balmam?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.smw.project.balmam.entity
  

##이미지 및 동영상 파일 upload directory 지정
file:
  upload:
    realPath: "C:/balmam/file-upload/"
    path: "/files"